import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'please',
  description: 'Generated by create next app',
}

export default function SelectLayout({ children }: { children: React.ReactNode }) {
  return <div className={inter.className}>{children}</div>
}
