import Footer from '@/components/footer'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'please 채용 공고',
  description: 'Generated by create next app',
}

export default function MyLayout({ children }: { children: React.ReactNode }) {
  return (
    <div className={`w-[23.4375rem] h-screen py-6 flex flex-col justify-between m-auto`}>
      {children}
      <Footer profile />
    </div>
  )
}
